[package]
name = "distil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
petgraph = "0.6.4"
serde_json = "1.0.108"
sqlparser = { path = "./sqlparser-rs"}
